from flask import Blueprint, request, jsonify, send_from_directory, current_app
from flask_jwt_extended import get_jwt_identity, get_jwt
from bson import ObjectId
from datetime import datetime, timezone
import os
import uuid
from extensions import mongo
from models.models import report_model, activity_log_model
from middleware.auth_middleware import jwt_required_custom
from services.report_service import generate_investigation_report

report_bp = Blueprint('reports', __name__)

def log_activity(user_id, username, action, resource_type, resource_id, details, ip=None):
    try:
        log = activity_log_model(user_id, username, action, resource_type, resource_id, details, ip)
        mongo.db.activity_logs.insert_one(log)
    except:
        pass

def serialize_report(r):
    r['_id'] = str(r['_id'])
    r['generated_at'] = str(r.get('generated_at', ''))
    return r

@report_bp.route('/generate/<case_id>', methods=['POST'])
@jwt_required_custom
def generate_report(case_id):
    claims = get_jwt()
    user_id = get_jwt_identity()
    username = claims.get('username')

    try:
        case = mongo.db.cases.find_one({"_id": ObjectId(case_id)})
        if not case:
            return jsonify({"error": "Case not found"}), 404

        evidence_list = list(mongo.db.evidence.find({
            "case_id": case_id, "is_deleted": False
        }))

        report_filename = f"report-{uuid.uuid4().hex}.pdf"
        report_dir = os.path.join(current_app.config['UPLOAD_FOLDER'], 'reports')
        report_path = os.path.join(report_dir, report_filename)

        generate_investigation_report(case, evidence_list, report_path, username)

        summary = f"Investigation report for case '{case.get('title')}' with {len(evidence_list)} evidence items."
        findings = [
            f"Total evidence collected: {len(evidence_list)}",
            f"Case status: {case.get('status', 'N/A')}",
            f"Case priority: {case.get('priority', 'N/A')}",
            f"Generated by: {username}"
        ]

        report = report_model(
            title=f"Investigation Report – {case.get('title')}",
            case_id=case_id,
            generated_by=username,
            file_path=f"/uploads/reports/{report_filename}",
            summary=summary,
            findings=findings
        )

        result = mongo.db.reports.insert_one(report)

        mongo.db.cases.update_one(
            {"_id": ObjectId(case_id)},
            {"$addToSet": {"report_ids": result.inserted_id},
             "$set": {"updated_at": datetime.now(timezone.utc)}}
        )

        log_activity(user_id, username, 'GENERATE_REPORT', 'report', result.inserted_id,
                     f"Generated report for case: {case.get('title')}", request.remote_addr)

        return jsonify({
            "message": "Report generated successfully",
            "report_id": str(result.inserted_id),
            "filename": report_filename
        }), 201

    except Exception as e:
        return jsonify({"error": str(e)}), 500

@report_bp.route('/', methods=['GET'])
@jwt_required_custom
def get_reports():
    claims = get_jwt()
    username = claims.get('username')
    role = claims.get('role')

    query = {}
    if role != 'admin':
        query['generated_by'] = username

    case_id = request.args.get('case_id', '')
    if case_id:
        query['case_id'] = case_id

    reports = list(mongo.db.reports.find(query).sort("generated_at", -1))
    return jsonify([serialize_report(r) for r in reports]), 200

@report_bp.route('/download/<report_id>', methods=['GET'])
@jwt_required_custom
def download_report(report_id):
    try:
        report = mongo.db.reports.find_one({"_id": ObjectId(report_id)})
        if not report:
            return jsonify({"error": "Report not found"}), 404

        filename = os.path.basename(report['file_path'])
        report_dir = os.path.join(current_app.root_path, current_app.config['UPLOAD_FOLDER'], 'reports')
        return send_from_directory(report_dir, filename, as_attachment=True,
                                   download_name=report.get('title', filename) + '.pdf')
    except Exception as e:
        return jsonify({"error": str(e)}), 400

@report_bp.route('/<report_id>', methods=['DELETE'])
@jwt_required_custom
def delete_report(report_id):
    claims = get_jwt()
    role = claims.get('role')
    if role != 'admin':
        return jsonify({"error": "Admin access required"}), 403
    try:
        mongo.db.reports.delete_one({"_id": ObjectId(report_id)})
        return jsonify({"message": "Report deleted"}), 200
    except Exception as e:
        return jsonify({"error": str(e)}), 400
